name: Java CI Build and Dist

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  JITPACK: true
  # This disables examplemod, and temporarily basemod and loader from being run in this action.
  # Its called JITPACK because jitpack uses the same variable, and we already check for it.
  # Check settings.gradle if you like.

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Make gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # LibGDX uses "./gradlew dist" instead of "./gradlew build"
    - name: Dist with Gradle Wrapper
      run: ./gradlew dist

    - name: Capture Desktop Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Desktop Artifacts
        path: desktop/build/libs/

    - name: Capture Server Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Server Artifacts
        path: server/build/libs/

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
